[tool.black]
line-length = 88
target-version = ["py37"]
include = '\.pyi?$'
# Se excluyen directorios y archivos que no deben formatearse
exclude = '''
/(
    \.git
  | \.venv
  | build
  | dist
  | __pycache__
)/
'''

[tool.flake8]
# Máxima longitud de línea y complejidad ciclomatica para mantener estándares rigurosos
max-line-length = 88
max-complexity = 10
extend-ignore = [
    "E203", # Ignora espacio antes de ':' (necesario para ser compatible con Black)
    "W503", # Ignora la ruptura de línea antes de operadores binarios (compatible con Black)
]
select = [
    "E",   # Errores de pycodestyle
    "W",   # Advertencias de pycodestyle
    "F",   # Errores de pyflakes
    "B",   # flake8-bugbear
    "C",   # Complejidad de McCabe
    "I",   # Orden de importaciones (flake8-import-order)
    "N",   # pep8-naming
    "Q",   # flake8-quotes
    "S",   # flake8-bandit
    "ANN", # flake8-annotations
    "BLK", # flake8-black
    "ERA", # flake8-eradicate
]

# Organización de importaciones: se utiliza el estilo "google" y se establecen los nombres de las importaciones de la aplicación
import-order-style = "google"
application-import-names = ["lgraph_essentials"]

exclude = [".git", "__pycache__", "build", "dist", "*.pyc", "*.egg-info"]

[tool.isort]
profile = "black"                     # Asegura compatibilidad con Black
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

# Configuración de quotes
inline-quotes = "double"
multiline-quotes = "double"
docstring-quotes = "double"

# Estadísticas
statistics = true
count = true
