curl -X 'GET' \
  'http://localhost:8000/health' \
  -H 'accept: application/json'


curl -X 'POST' \
  'http://localhost:8000/invoke' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "message": "Hola",
  "model": "gpt-4o-mini",
  "thread_id": "847c6285-8fc9-4560-a83f-4e6285809254"
}'


curl -X 'POST' \
  'http://localhost:8000/stream' \
  -H 'accept: text/event-stream' \
  -H 'Content-Type: application/json' \
  -d '{
  "message": "Hola?",
  "model": "gpt-4o-mini",
  "thread_id": "847c6285-8fc9-4560-a83f-4e6285809258",
  "stream_tokens": true
}'
